"""empty message

Revision ID: bd56899a74e6
Revises: 
Create Date: 2025-02-25 19:18:46.732645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd56899a74e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('phone_number', name='users_phone_number_key')
    )
    # ### end Alembic commands ###


# Я НЕ ЗНАЮ, КАК ЭТО РАБОТАЕ, НО ДАННЫЕ ОН ОБНОВЛЯЕТ С ПОМОЩЬЮ downgrade